version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_web_design
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: web_design_db
    ports:
      - "5433:5432"
    volumes:
      # On lie ton dossier local ./sql au dossier d'initialisation de Postgres
      - ./sql:/docker-entrypoint-initdb.d/

  tomcat:
    build: .
    container_name: tomcat_app
    volumes:
      - ./src/main/webapp/assets/uploads:/uploads_data
      - ./server.xml:/usr/local/tomcat/conf/server.xml
    ports:
      - "8081:8080"
    depends_on:
      - db